### ISSUE TITLE
API 9

### ISSUE THREAD

**Issue by drejjmit** [marimelon/RememberAskingPrice#3]
Not sure if you still play the game, but this stopped working with Dalamud changing to API 9. Hopefully you'll get the time to fix it :)

**Comment by marimelon** [comment]
Updated.(ver 0.4.0.1)
However, I was not able to fully test it because my development PC is broken.
If you have any problems, please reopen the issue.

**Comment by drejjmit** [comment]
Worked fine during the quick testing i did. Thank you for the update 👍
